openapi: 3.0.0
info:
  description: "Internal Booking"
  version: "1.0.1"
  title: "Swagger Internal Booking "
servers:
  - url: http://localhost:8080/internal-domain/

paths:
  /v1/trade/create:
    post:
      tags:
        - "Trade"
      summary: "Post create trade"
      description: ""
      operationId: "postCreateTrade"
      requestBody:
        description: Body for create trade
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateTradeRequest"
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateTradeResponse"
  /v1/trade/report:
    post:
      tags:
        - "Trade"
      summary: "Post generate trade report"
      description: ""
      operationId: "postGenerateReport"
      requestBody:
        description: Body for generate trade report
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GenerateReportRequest"
      responses:
        "201":
          description: "successful operation"


components:
  schemas:
    CreateTradeRequest:
      type: object
      properties:
        productId:
          type: string
          example: "P1"
        tradeDate:
          type: string
        isBuy:
          type: boolean
        qty:
          type: integer
          example: 10000
        price:
          type: number
          example: 1.067591
        brokerId:
          type: string
          example: "B1"
    CreateTradeResponse:
      type: object
      properties:
        tradeId:
          type: string
          example: "T1"
    GenerateReportRequest:
      type: object
      properties:
        productType:
          type: string
          example: "SWP"
        productSubType:
          type: string
          example: "Interest_Rate"
        brokerId:
          type: string
        tradeDate:
          type: string
          example: "2023-12-08T07:00:00.000Z"
    GenerateReportGenericRequest:
      type: array
      items:
        $ref: "#/components/schemas/Generic"
    Generic:
      type: object
      properties:
        key:
          type: string
          example: productId
        value:
          type: string
          example: p1